
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.4
 * Fri Nov 15 09:44:14 WET 2024
 * Generated source version: 3.6.4
 */

@XmlRootElement(name = "marcarConsultas_Server", namespace = "http://default_package/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marcarConsultas_Server", namespace = "http://default_package/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4", "arg5", "arg6"})

public class MarcarConsultas_Server {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private int arg1;
    @XmlElement(name = "arg2")
    private int arg2;
    @XmlElement(name = "arg3")
    private int arg3;
    @XmlElement(name = "arg4")
    private int arg4;
    @XmlElement(name = "arg5")
    private int arg5;
    @XmlElement(name = "arg6")
    private int arg6;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public int getArg2() {
        return this.arg2;
    }

    public void setArg2(int newArg2)  {
        this.arg2 = newArg2;
    }

    public int getArg3() {
        return this.arg3;
    }

    public void setArg3(int newArg3)  {
        this.arg3 = newArg3;
    }

    public int getArg4() {
        return this.arg4;
    }

    public void setArg4(int newArg4)  {
        this.arg4 = newArg4;
    }

    public int getArg5() {
        return this.arg5;
    }

    public void setArg5(int newArg5)  {
        this.arg5 = newArg5;
    }

    public int getArg6() {
        return this.arg6;
    }

    public void setArg6(int newArg6)  {
        this.arg6 = newArg6;
    }

}

