package default_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-11-13T10:31:51.268Z
 * Generated source version: 3.6.4
 *
 */
@WebService(targetNamespace = "http://default_package/", name = "FrontEnd_Clinica")
@XmlSeeAlso({ObjectFactory.class})
public interface FrontEndClinica {

    @WebMethod(operationName = "listarConsultas_Server")
    @RequestWrapper(localName = "listarConsultas_Server", targetNamespace = "http://default_package/", className = "default_package.ListarConsultasServer")
    @ResponseWrapper(localName = "listarConsultas_ServerResponse", targetNamespace = "http://default_package/", className = "default_package.ListarConsultasServerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listarConsultasServer(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws NotBoundException_Exception, MalformedURLException_Exception;

//	@WebMethod
//    @RequestWrapper(localName = "verConsultas", targetNamespace = "http://default_package/", className = "default_package.VerConsultas")
//    @ResponseWrapper(localName = "verConsultasResponse", targetNamespace = "http://default_package/", className = "default_package.VerConsultasResponse")
//    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String verConsultas(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
